### ISSUE TITLE
url parameter base fixed verion strategy  [SPR-15892]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#20446]
**[Zsolt Fatér](https://jira.spring.io/secure/ViewProfile.jspa?name=fater.zsolt@gmail.com)** opened **[SPR-15892](https://jira.spring.io/browse/SPR-15892?redirect=false)** and commented

Pull request url: https://github.com/spring-projects/spring-framework/pull/1503

Prefix based version path strategy has a problem with css.

If css include any relative url, the server can not resolve relative url, because it has two version prefix in the url.

Example

The version: 1.0.0

The css url: http://localhost/application/1.0.0/css/test.css

Original css content

```css
body {
    background-image: url("img/picture.jpg");
    background-size: cover;
}
```

Modified css content

```css
body {
    background-image: url("1.0.0/img/picture.jpg");
    background-size: cover;
}
```

The picture.jpg url will be: http://localhost/application/1.0.0/css/1.0.0/img/picture.jpg but the expected is http://locahost/application/1.0.0/css/img/picture.jpg

Solution

We was make the UrlParameterFixedVersrionStrategy class.

The css url: http://localhost/application/css/test.css?v=1.0.0

Modified css content

```css
body {
    background-image: url("img/picture.jpg?v=1.0.0");
    background-size: cover;
}
```

the picture.jpg url: http://localhost/application/css/img/picture.jpg?v=1.0.0

MvcConfig example

```java
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter;
import org.springframework.web.servlet.resource.AbstractVersionStrategy;
import org.springframework.web.servlet.resource.UrlParameterFixedVersionStrategy;
import org.springframework.web.servlet.resource.VersionResourceResolver;

@Configuration
@ComponentScan({"test.controller"})
public class MvcConfig extends WebMvcConfigurerAdapter {

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        AbstractVersionStrategy fixedVersionStrategy = new UrlParameterFixedVersionStrategy("1.0.0");
        VersionResourceResolver versionResourceResolver = new VersionResourceResolver()
                .addVersionStrategy(fixedVersionStrategy, "/**");

        registry.addResourceHandler("/**")
                .addResourceLocations("classpath:/other-resources/")
                .resourceChain(true)
                .addResolver(versionResourceResolver);
    }

}
```

---

**Reference URL:** https://github.com/spring-projects/spring-framework/pull/1503
