### ISSUE TITLE
 In the yaml file, use @Value annotation to parse the attribute to get an error value

### ISSUE THREAD

**Issue by SmilingBug** [spring-projects/spring-framework#25208]
My configuration file is application.yml, and the content is as follows:
```
bizlimit:
  common:
    startTime: 05:00
    endTime: 23:00
```

Java code:
```
@Component
public class BizTimeLimitProperties {
    @Value("${bizlimit.common.startTime}")
    private String startTime;
    @Value("${bizlimit.common.endTime}")
    private String endTime;
}
```

In debug mode, I found that startTime is correct, but endTime is '1380'
