### ISSUE TITLE
DataSourceInitializer does not work with spring.datasource.hikari.auto-commit=false

### ISSUE THREAD

**Issue by sixrandanes** [spring-projects/spring-framework#27008]
Hello, 

I would like to submit an issue. I am facing a problem with creation of spring-batch tables when you use a datasource in `auto-commit mode => false;`

My project is using spring-boot@2.2.7 and postgresql.

Here is my configuration :

```
spring:
  batch:
    initialize-schema: always

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: Hikari
      auto-commit: false
```	  

I have checked the `BatchDataSourceInitializer` class which is the subclass of `AbstractDataSourceInitializer`.
It appears that the code at line 65 `DatabasePopulatorUtils.execute(populator, this.dataSource);` is responsible for running the sql script of spring-batch tables, with spring-jdbc, but the transaction is never committed.
And consequently, my tables are never created in my database.

If I switch the configuration of my datasource, ie `auto-commit: true`, everything is working fine.

I was expecting my spring-batch tables be created (initialize-schema => always) even if my datasource is not in auto-commit mode.
It's not so easy and not very intuitive, at first sight, to discover why the tables are not created. We first think about a misconfiguration relative to spring-batch but nothing related to datasource configuration.

What do you think about that ?

Thanks for your help.
