### ISSUE TITLE
[Bug] YamlPropertiesFactoryBean incorrect flatten nested map to properties when map key contains escaped brackets

### ISSUE THREAD

**Issue by ian4hu** [spring-projects/spring-framework#27020]
**Affects:** since 4.1

---

Yaml file like bellow:

```yaml
root:
  webservices:
    "[domain.test:8080]":
      - username: me
        password: mypassword

```

should equals properties file like:

```properties
root.webservices[[domain.test\:8080]][0].username=me
root.webservices[[domain.test\:8080]][0].password=mypassword
```

or:

```properties
root.webservices[[domain.test\:8080]][0].username=me
root.webservices[[domain.test\:8080]][0].password=mypassword
```

Both properties file is parseable for Spring Boot [Binding Maps](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.external-config.typesafe-configuration-properties.relaxed-binding.maps)
