### ISSUE TITLE
Request to make properties for IAM on R2DBC more clear

### ISSUE THREAD

**Issue by dvrietschoten** [spring-projects/spring-framework#29878]
**Affects:** Sping boot 3.0.1

I'm trying to use IAM on google cloud sql in combination with Spring boot and R2DBC.
My application.yml contains:
```
spring:
  cloud:
    gcp:
      project-id: ...
      sql:
        database-name: ...
        enable-iam-auth: true
        instance-connection-name: ...
  r2dbc:
    username: ...
    password: IgnoredButRequired
```
The r2dbc url gets constructed using properties from spring.cloud.sql (database name and instance-connection-name). However, the enable-iam-auth is not used. In order to make IAM work for R2DBC, I have to specify:
spring.r2dbc.properties.ENABLE_IAM_AUTH=true

It is not very clear that this property needs to be set. It would be more clear if spring.cloud.sql.enable-iam-auth is used (as is done with database-name and instance-connection-name).
