### ISSUE TITLE
support spel in yaml config

### ISSUE THREAD

**Issue by timnick-snow** [spring-projects/spring-framework#30448]
```java
@ConfigurationProperties(prefix = "foo")
@Data
public class DemoConfig {
    private long timeout;
    private int count;
    private String other;
}
```

```yaml
foo:
  timeout: ${60*1000}
  count: 10
  other: ${'hello '+'world'}
```

expect timeou = 60000 and  other="hello world". 
but it failed to start up
Reason: failed to convert java.lang.String to long (caused by java.lang.NumberFormatException: For input string: "${60*1000}")
