### ISSUE TITLE
hibernate isolation property `release_mode` -> on_close not working

### ISSUE THREAD

**Issue by Jeffrey-Oh** [spring-projects/spring-framework#32556]
```
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.4'
    id 'io.spring.dependency-management' version '1.1.4'
}

group = 'com.testtest.hibernate'
version = ''

java {
    sourceCompatibility = '17'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    // lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

    // atomikos
    implementation 'com.atomikos:transactions-spring-boot3-starter:6.0.0'

    // Hibernate
    implementation group: 'com.vladmihalcea', name: 'hibernate-types-52', version: '2.9.12'
    implementation group: 'org.hibernate', name: 'hibernate-core', version: '6.2.3.Final'

    // jpa
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // jdbc
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'

    // mysql
    implementation group: 'mysql', name: 'mysql-connector-java', version: '8.0.27'

    implementation 'javax.xml.bind:jaxb-api:2.4.0-b180830.0359'
}

test {
    useJUnitPlatform()
}
```
---
```
spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        connection:
          handling_mode: DELAYED_ACQUISITION_AND_HOLD
          provider_disables_autocommit: false
          release_mode: on_close
        dialect: org.hibernate.dialect.MySQLDialect
      jdbc:
        order_updates: true
        batch_versioned_data: false

  main:
    allow-bean-definition-overriding: true
```
---
When migrating from the existing Spring Boot version `2.4.1 to 3.2.4`, I encountered a question. When the following property is defined in hibernate-core(? or hibernate-orm) (Spring Boot version 2.4.1), it seems to be applied correctly:

spring.jpa.properties.hibernate.connection.release_mode=on_close

However, when using Hibernate-core version `6.2.3.Final` in version `3.2.4` (`starting from the minimum version supporting 3.x`), this option is not applied, and it continues to be applied as after_statement. If I need to override the isolation property of the `@Transactional` annotation, the error occurs as follows because `session.getJdbcCoordinator().getLogicalConnection().getConnectionHandlingMode().getReleaseMode()` at line 92 of `HibernateJpaDialect.class` is not `ON_CLOSE`:

> HibernateJpaDialect is not allowed to support custom isolation levels: make sure that its 'prepareConnection' flag is on (the default) and that the Hibernate connection release mode is set to ON_CLOSE.

Additionally, I have tested setting the value declared in `PhysicalConnectionHandlingMode.class`, `DELAYED_ACQUISITION_AND_HOLD`, as `spring.jpa.properties.hibernate.connection.handling_mode=DELAYED_ACQUISITION_AND_HOLD`, but the same error occurs. Is it not possible for users to control this value in the latest version? If not, could you please provide specific guidance on why this is not possible, who is responsible for calling this option, and any alternative solutions? If all of the above is an issue with the current version, I would like to request a fix.
