### ISSUE TITLE
JMS messages lack tracing information

### ISSUE THREAD

**Issue by kropptrevor** [spring-projects/spring-framework#33898]
Java Spring Boot version: 3.5.5
Java OTEL version: 2.10.0

ActiveMQ version: 5.8.5
Aspire image: mcr.microsoft.com/dotnet/aspire-dashboard:8.1.0
OTEL Collector image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.113.0

Infrastructure:
```
Java Application JMS --> ActiveMQ
Java Application Tracing --[http/protobuf]--> OTEL Collector --[OTLP/gRPC]--> Aspire
```

Dependencies: [deps-tree.txt](https://github.com/user-attachments/files/17783038/deps-tree.txt)
Reproducible example: [example.zip](https://github.com/user-attachments/files/17783050/example.zip)

I used Aspire to verify that traces were being recorded:
![image](https://github.com/user-attachments/assets/1692bfa9-2bcb-4d1e-98ea-fd6a1e6d12cb)

I checked the ActiveMQ console to view the properties of the messages:
![image](https://github.com/user-attachments/assets/690e9a9c-79c6-42e9-b8f2-3659af814b0a)

I verified that the `JmsTemplate` was using an instance of `io.micrometer.observation.SimpleObservationRegistry`.

The `MessageProducer` being used is `org.apache.activemq.ActiveMQMessageProducer`.

It seems to me that the method `io.micrometer.jakarta9.instrument.jms.JmsPublishObservationContext::getSetter` is never called, although `setter` seems to be doing the work of adding properties to the `Message`.

I am expecting that
1. A span shows for sending the JMS `Message`, but the only span present is for the HTTP request that triggered it
2. Tracing metadata to be present in the `Message` properties, but there are no properties set in the resulting message

**Comment by bclozel** [comment]
Hello @kropptrevor I think you meant to [report this issue against opentelemetry support](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues) because your project is not using Micrometer but instead the unofficial Spring integration with OpenTelemetry.

**Comment by bclozel** [comment]
I modified your sample application to make sure that tracing was working as expected.
I removed all io.opentelemetry dependencies and used instead a local zipkin setup (using [OpenTelemetry is first class supported](https://spring.io/blog/2024/10/28/lets-use-opentelemetry-with-spring)).

```xml
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-brave</artifactId>
        </dependency>
        <dependency>
            <groupId>io.zipkin.reporter2</groupId>
            <artifactId>zipkin-reporter-brave</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-docker-compose</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>
```

Added the following docker-compose.yml
```yml
services:
  activemq:
    container_name: activemq
    image: apache/activemq-artemis:latest-alpine
    ports:
      - 61616:61616
      - 8161:8161
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    restart: always
    ports:
      - 9411:9411
```

I also removed the custom `JmsListenerContainerFactory` bean definition as this is done for you.
Used the modified application properties:

```yml
spring:
    application:
        name: jms-otel
    activemq:
        password: artemis
        user: artemis

management:
    tracing:
        sampling:
            probability: 1 # for testing purposes
```

I'm seeing traces as expected:

![image](https://github.com/user-attachments/assets/80fd2535-0d40-483d-885f-56409afa50c4)
